"""CSV Configuration untuk ETL Dashboard."""

# Config per report type - simple dict approach
CSV_CONFIGS = {
    "transaksi": {
        "expected_headers": [
            "DateTime",
            "Transaction Type",
            "Channel",
            "Region",
            "Area",
            "Sales Area",
            "Cluster",
            "Additional Territory",
            "Transaction ID",
            "Transaction Channel",
            "Organization Type",
            "Organization ID",
            "Organization Name",
            "Operator ID",
            "Operator Name",
            "Operator Type",
            "MSISDN",
            "User Name",
            "B# MSISDN",
            "Dompetku MSISDN",
            "Product Group",
            "Product Name",
            "Voucher Type",
            "Bill Company",
            "Bill Number",
            "Main Price",
            "Discount(IDR)",
            "Amount_Debit(IDR)",
            "Final transaction status",
            "Surrouding Status",
            "Reversal Transaction ID",
            "Reversed DateTime",
            "Reversed Status",
            "ACommissionResult",
            "BCommissionResult",
            "ADIscountResult",
            "BDiscountResult",
            "DiscountRuleName",
            "CommissionSchema",
            "MSISDNTerritoryVerificationResult",
            "A_LAC",
            "A_CI",
            "B_LAC",
            "B_CI",
            "Wallet Type",
            "SP Status",
            "Service Type",
        ],
        "display_columns": [
            "DateTime",
            "Transaction Type",
            "Channel",
            "Region",
            "Transaction ID",
            "Organization Name",
            "Product Name",
            "Main Price",
            "Amount_Debit(IDR)",
            "Final transaction status",
        ],
        "metadata_skip_patterns": [
            "Transaction Details Report",
            "Start Date:",
            "End Date:",
        ],
    },
    "komisi": {
        "expected_headers": [
            "DateTime",
            "Transaction Type",
            "Channel",
            "Region",
            "Area",
            "Sales Area",
            "Cluster",
            "Additional Territory",
            "Account Type",
            "Transaction ID",
            "Transaction Channel",
            "Organization Type",
            "Organization ID",
            "Organization Name",
            "Schema ID",
            "Schema Name",
            "Incentive source organization",
            "Incentive Balance Amount",
            "Incentive KOIN Amount",
        ],
        "display_columns": [
            "DateTime",
            "Transaction Type",
            "Channel",
            "Region",
            "Transaction ID",
            "Organization Name",
            "Schema Name",
            "Incentive Balance Amount",
            "Incentive KOIN Amount",
        ],
        "metadata_skip_patterns": [
            "Commission and Incentive Details Report",
            "Start Date:",
            "End Date:",
        ],
    },
}


def get_csv_config(report_type: str) -> dict:
    """Get configuration untuk report type tertentu."""
    return CSV_CONFIGS.get(report_type, {})
