from typing import Protocol

from models.user_model import User


class IUserRepository(Protocol):
    def get_by_username(self, username: str) -> User | None: ...
    def get_by_id(self, user_id: int) -> User | None: ...
    def add_user(self, user: User) -> None: ...
    def update(self, user: User) -> None: ...
